[package]
name = "russel"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
winreg = "0.52.0"
actix-web = "4.0"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.38.0"